package main

import "testing"

func TestServerHandlesXaddExplicitID(t *testing.T) {
	server := newServer()

	if got := string(server.handleCommand([]string{"XADD", "mystream", "1526919030474-0", "temperature", "36", "humidity", "95"})); got != "$15\r\n1526919030474-0\r\n" {
		t.Fatalf("XADD response = %q, want inserted ID", got)
	}

	entry, ok := server.getLiveEntry("mystream")
	if !ok {
		t.Fatal("mystream key missing after XADD")
	}
	if entry.value.typ != streamValue {
		t.Fatalf("entry type = %v, want stream", entry.value.typ)
	}
	if len(entry.value.stream.entries) != 1 {
		t.Fatalf("stream entry count = %d, want 1", len(entry.value.stream.entries))
	}

	streamEntry := entry.value.stream.entries[0]
	if streamEntry.id.ms != 1526919030474 || streamEntry.id.seq != 0 {
		t.Fatalf("stream ID = %+v, want 1526919030474-0", streamEntry.id)
	}
	if len(streamEntry.fields) != 2 {
		t.Fatalf("field count = %d, want 2", len(streamEntry.fields))
	}
	if streamEntry.fields[0] != (streamField{key: "temperature", value: "36"}) {
		t.Fatalf("first field = %+v", streamEntry.fields[0])
	}
}

func TestServerRejectsXaddNonIncreasingID(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "mystream", "1-1", "field", "value"})

	if got := string(server.handleCommand([]string{"XADD", "mystream", "1-1", "field", "value"})); got != "-ERR The ID specified in XADD is equal or smaller than the target stream top item\r\n" {
		t.Fatalf("XADD duplicate ID response = %q", got)
	}
	if got := string(server.handleCommand([]string{"XADD", "mystream", "1-0", "field", "value"})); got != "-ERR The ID specified in XADD is equal or smaller than the target stream top item\r\n" {
		t.Fatalf("XADD smaller ID response = %q", got)
	}
}

func TestServerHandlesXaddPartialAutoGeneratedID(t *testing.T) {
	server := newServer()

	if got := string(server.handleCommand([]string{"XADD", "mystream", "0-*", "field", "value"})); got != "$3\r\n0-1\r\n" {
		t.Fatalf("XADD 0-* response = %q, want 0-1", got)
	}
	if got := string(server.handleCommand([]string{"XADD", "mystream", "1-*", "field", "value"})); got != "$3\r\n1-0\r\n" {
		t.Fatalf("XADD 1-* response = %q, want 1-0", got)
	}
	if got := string(server.handleCommand([]string{"XADD", "mystream", "1-*", "field", "value"})); got != "$3\r\n1-1\r\n" {
		t.Fatalf("second XADD 1-* response = %q, want 1-1", got)
	}
	if got := string(server.handleCommand([]string{"XADD", "mystream", "2-*", "field", "value"})); got != "$3\r\n2-0\r\n" {
		t.Fatalf("XADD 2-* response = %q, want 2-0", got)
	}
}

func TestServerRejectsInvalidXadd(t *testing.T) {
	server := newServer()

	tests := [][]string{
		{"XADD", "mystream", "0-0", "field", "value"},
		{"XADD", "mystream", "abc", "field", "value"},
		{"XADD", "mystream", "1-a", "field", "value"},
		{"XADD", "mystream", "1--1", "field", "value"},
		{"XADD", "mystream", "1-1", "field"},
	}

	for _, command := range tests {
		if got := string(server.handleCommand(command)); got == "$3\r\n1-1\r\n" || got == "+OK\r\n" {
			t.Fatalf("command %v succeeded unexpectedly with response %q", command, got)
		}
	}
}

func TestServerRejectsXaddWrongType(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"SET", "mystream", "value"})

	if got := string(server.handleCommand([]string{"XADD", "mystream", "1-0", "field", "value"})); got != "-WRONGTYPE Operation against a key holding the wrong kind of value\r\n" {
		t.Fatalf("XADD wrong type response = %q", got)
	}
}

func TestServerHandlesXrangeFullRange(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "mystream", "1-0", "temperature", "36", "humidity", "95"})
	server.handleCommand([]string{"XADD", "mystream", "2-0", "temperature", "37"})

	want := "*2\r\n" +
		"*2\r\n$3\r\n1-0\r\n*4\r\n$11\r\ntemperature\r\n$2\r\n36\r\n$8\r\nhumidity\r\n$2\r\n95\r\n" +
		"*2\r\n$3\r\n2-0\r\n*2\r\n$11\r\ntemperature\r\n$2\r\n37\r\n"
	if got := string(server.handleCommand([]string{"XRANGE", "mystream", "-", "+"})); got != want {
		t.Fatalf("XRANGE full response = %q, want %q", got, want)
	}
}

func TestServerHandlesXrangeSubRange(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "mystream", "1-0", "field", "a"})
	server.handleCommand([]string{"XADD", "mystream", "1-1", "field", "b"})
	server.handleCommand([]string{"XADD", "mystream", "2-0", "field", "c"})

	want := "*1\r\n*2\r\n$3\r\n1-1\r\n*2\r\n$5\r\nfield\r\n$1\r\nb\r\n"
	if got := string(server.handleCommand([]string{"XRANGE", "mystream", "1-1", "1-1"})); got != want {
		t.Fatalf("XRANGE exact response = %q, want %q", got, want)
	}

	want = "*2\r\n" +
		"*2\r\n$3\r\n1-0\r\n*2\r\n$5\r\nfield\r\n$1\r\na\r\n" +
		"*2\r\n$3\r\n1-1\r\n*2\r\n$5\r\nfield\r\n$1\r\nb\r\n"
	if got := string(server.handleCommand([]string{"XRANGE", "mystream", "1", "1"})); got != want {
		t.Fatalf("XRANGE millisecond response = %q, want %q", got, want)
	}
}

func TestServerHandlesEmptyXrange(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "mystream", "1-0", "field", "value"})

	tests := [][]string{
		{"XRANGE", "missing", "-", "+"},
		{"XRANGE", "mystream", "2-0", "3-0"},
		{"XRANGE", "mystream", "1-1", "1-2"},
	}

	for _, command := range tests {
		if got := string(server.handleCommand(command)); got != "*0\r\n" {
			t.Fatalf("command %v response = %q, want empty array", command, got)
		}
	}
}

func TestServerRejectsInvalidXrange(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"SET", "mystream", "value"})

	if got := string(server.handleCommand([]string{"XRANGE", "mystream", "-", "+"})); got != "-WRONGTYPE Operation against a key holding the wrong kind of value\r\n" {
		t.Fatalf("XRANGE wrong type response = %q", got)
	}

	tests := [][]string{
		{"XRANGE", "mystream", "abc", "+"},
		{"XRANGE", "mystream", "1-a", "+"},
		{"XRANGE", "mystream", "1--1", "+"},
		{"XRANGE", "mystream", "-", "*"},
	}

	for _, command := range tests {
		if got := string(server.handleCommand(command)); got != "-ERR Invalid stream ID specified as stream command argument\r\n" {
			t.Fatalf("command %v response = %q, want invalid stream ID error", command, got)
		}
	}
}

func TestServerHandlesXreadSingleStream(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "mystream", "1-0", "field", "a"})
	server.handleCommand([]string{"XADD", "mystream", "1-1", "field", "b"})
	server.handleCommand([]string{"XADD", "mystream", "2-0", "field", "c"})

	want := "*1\r\n" +
		"*2\r\n$8\r\nmystream\r\n*2\r\n" +
		"*2\r\n$3\r\n1-1\r\n*2\r\n$5\r\nfield\r\n$1\r\nb\r\n" +
		"*2\r\n$3\r\n2-0\r\n*2\r\n$5\r\nfield\r\n$1\r\nc\r\n"
	if got := string(server.handleCommand([]string{"XREAD", "STREAMS", "mystream", "1-0"})); got != want {
		t.Fatalf("XREAD single stream response = %q, want %q", got, want)
	}
}

func TestServerHandlesXreadMultipleStreams(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "stream1", "1-0", "field", "a"})
	server.handleCommand([]string{"XADD", "stream1", "2-0", "field", "b"})
	server.handleCommand([]string{"XADD", "stream2", "1-0", "other", "c"})

	want := "*2\r\n" +
		"*2\r\n$7\r\nstream1\r\n*1\r\n*2\r\n$3\r\n2-0\r\n*2\r\n$5\r\nfield\r\n$1\r\nb\r\n" +
		"*2\r\n$7\r\nstream2\r\n*1\r\n*2\r\n$3\r\n1-0\r\n*2\r\n$5\r\nother\r\n$1\r\nc\r\n"
	if got := string(server.handleCommand([]string{"XREAD", "STREAMS", "stream1", "stream2", "1-0", "0-0"})); got != want {
		t.Fatalf("XREAD multi stream response = %q, want %q", got, want)
	}
}

func TestServerHandlesXreadSkippingStreamsWithoutNewEntries(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "stream1", "1-0", "field", "a"})
	server.handleCommand([]string{"XADD", "stream2", "1-0", "field", "b"})
	server.handleCommand([]string{"XADD", "stream2", "2-0", "field", "c"})

	want := "*1\r\n" +
		"*2\r\n$7\r\nstream2\r\n*1\r\n*2\r\n$3\r\n2-0\r\n*2\r\n$5\r\nfield\r\n$1\r\nc\r\n"
	if got := string(server.handleCommand([]string{"XREAD", "STREAMS", "missing", "stream1", "stream2", "0-0", "1-0", "1-0"})); got != want {
		t.Fatalf("XREAD skip empty streams response = %q, want %q", got, want)
	}
}

func TestServerHandlesEmptyXread(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"XADD", "mystream", "1-0", "field", "value"})

	tests := [][]string{
		{"XREAD", "STREAMS", "missing", "0-0"},
		{"XREAD", "STREAMS", "mystream", "1-0"},
		{"XREAD", "STREAMS", "missing", "mystream", "0-0", "1-0"},
	}

	for _, command := range tests {
		if got := string(server.handleCommand(command)); got != "*-1\r\n" {
			t.Fatalf("command %v response = %q, want null array", command, got)
		}
	}
}

func TestServerRejectsInvalidXread(t *testing.T) {
	server := newServer()
	server.handleCommand([]string{"SET", "mystream", "value"})

	if got := string(server.handleCommand([]string{"XREAD", "STREAMS", "mystream", "0-0"})); got != "-WRONGTYPE Operation against a key holding the wrong kind of value\r\n" {
		t.Fatalf("XREAD wrong type response = %q", got)
	}

	tests := [][]string{
		{"XREAD", "mystream", "0-0"},
		{"XREAD", "STREAMS", "mystream"},
		{"XREAD", "STREAMS", "mystream", "other", "0-0"},
		{"XREAD", "STREAMS", "mystream", "abc"},
		{"XREAD", "STREAMS", "mystream", "1-a"},
	}

	for _, command := range tests {
		if got := string(server.handleCommand(command)); got == "*-1\r\n" || got[0] != '-' {
			t.Fatalf("command %v succeeded unexpectedly with response %q", command, got)
		}
	}
}
